---
- name: Install Apache web server
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy virtual host configuration
      template:
        src: vhost.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify:
        - Restart apache

    - name: Enable Apache mod_rewrite
      apache2_module:
        name: rewrite
        state: present

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
