- name: Install and configure Apache, PHP, and MySQL
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Install PHP and required modules
      apt:
        name:
          - php8.1
          - php8.1-cli
          - php8.1-mysql
          - libapache2-mod-php8.1
        state: present
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: yes

- name: Deploy the application
  hosts: webservers
  become: yes
  tasks:
    - name: Clone the repository
      git:
        repo: https://github.com/udaykarmakar/ExamSeatArrangementSystem.git
        dest: /var/www/html/exam_seat
        version: master

    - name: Set permissions for the project
      file:
        path: /var/www/html/exam_seat
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
